import {BeatAudio} from './audio.js';
import {TRACKS} from './tracks.js';
import {LIMITS,POINTS,judge,updateStat,selectWords,choicesFor,summarize,weak} from './core.js';
import {openDB,all,saveSettings,saveProgress,saveSession} from './db.js';
const $=s=>document.querySelector(s), main=$('#main'), audio=new BeatAudio();
const defaults={difficulty:'NORMAL',count:20,target:'all',track:'focus',bgm:.38,voice:.85,se:.55,voiceOn:true};
let settings={...defaults},words=[],stats={},sessions=[],db,page='play',game=null,raf=0,saveChain=Promise.resolve(),preview=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>`${Math.round(n*100)}%`, sec=n=>`${(n/1000).toFixed(2)}秒`, fmt=n=>n.toLocaleString('ja-JP');
const pos={verb:'動詞',noun:'名詞',adjective:'形容詞',adverb:'副詞'};
function notice(s){$('#notice').textContent=s;$('#notice').hidden=!s;}
function queueSave(task){saveChain=saveChain.then(task).catch(e=>{notice('記録の保存に失敗しました。この画面を閉じず、設定の「保存を再試行」を押してください。');console.error(e);});return saveChain;}
function persistSettings(){audio.update(settings);if(db)queueSave(()=>saveSettings(db,{...settings}));}
function controls(name,items){return `<div class="chips" data-control="${name}">${items.map(([v,label])=>`<button data-value="${v}" class="${String(settings[name])===String(v)?'selected':''}" aria-pressed="${String(settings[name])===String(v)}">${label}</button>`).join('')}</div>`;}
function targetOptions(){return [['all',`全${words.length}語`],...Array.from({length:5},(_,i)=>[`level${i+1}`,`Level ${i+1}`]),['weak','苦手単語のみ'],['new','未学習単語中心']].map(([v,l])=>`<option value="${v}" ${settings.target===v?'selected':''}>${l}</option>`).join('');}
function renderHome(){const answers=sessions.flatMap(s=>s.answers),summary=summarize(answers);const today=new Date().toLocaleDateString('sv-SE');const todayCount=answers.filter(a=>new Date(a.at).toLocaleDateString('sv-SE')===today).length;const best=Math.max(0,...sessions.map(s=>summarize(s.answers).score)),combo=Math.max(0,...sessions.map(s=>summarize(s.answers).bestCombo));const t=TRACKS.find(t=>t.id===settings.track);
 main.innerHTML=`<section class="hero"><div class="eyebrow">FIND YOUR LEARNING RHYTHM</div><div class="hero-art" aria-hidden="true">A♪</div><h1>英単語を、<br>リズムにのせて。</h1><p>見る。聴く。選ぶ。少しずつ、速く。</p></section><div class="today"><span>✦ 今日の学習</span><span><strong>${todayCount}</strong><small>words</small></span></div><section class="card"><div class="field"><span class="label">SPEED / 回答スピード</span>${controls('difficulty',Object.keys(LIMITS).map(k=>[k,k]))}<p class="muted" id="speedHelp" style="margin:8px 0 0;font-size:10px">回答時間 ${LIMITS[settings.difficulty]/1000}秒 · 早く正解するほど高得点</p></div><div class="grid2"><label class="field"><span class="label">WORDS / 出題範囲</span><select id="target">${targetOptions()}</select></label><label class="field"><span class="label">LENGTH / 問題数</span><select id="count">${[10,20,30,50].map(n=>`<option ${settings.count===n?'selected':''}>${n}</option>`).join('')}</select></label></div><span class="label">YOUR SOUNDTRACK</span><div class="track-card"><div class="track-icon">♫</div><div class="grow"><select id="track" aria-label="BGM">${TRACKS.map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${x.name}</option>`).join('')}</select><small id="trackInfo">${t.bpm} BPM · ${t.style}</small></div><button id="preview" class="icon-button" aria-label="${preview?'試聴を停止':'BGMを試聴'}">${preview?'Ⅱ':'▷'}</button></div><button class="primary wide" id="start">START <span style="float:right">→</span></button></section><div class="stats"><div><small>BEST SCORE</small><strong>${fmt(best)}</strong></div><div><small>BEST COMBO</small><strong>${combo}</strong></div><div><small>ACCURACY</small><strong>${answers.length?pct(summary.accuracy):'—'}</strong></div></div><p class="muted" style="text-align:center;font-size:10px">500語 · 5つのレベル · あなたのペースで</p>`;
 main.querySelectorAll('[data-control] button').forEach(b=>b.onclick=()=>{settings.difficulty=b.dataset.value;persistSettings();renderHome();});$('#target').onchange=e=>{settings.target=e.target.value;persistSettings();};$('#count').onchange=e=>{settings.count=Number(e.target.value);persistSettings();};$('#track').onchange=e=>{settings.track=e.target.value;persistSettings();const tr=TRACKS.find(x=>x.id===settings.track);$('#trackInfo').textContent=`${tr.bpm} BPM · ${tr.style}`;if(preview)audio.start();};$('#preview').onclick=async()=>{await initAudio();preview=!preview;if(preview)audio.start();else audio.stopMusic();$('#preview').textContent=preview?'Ⅱ':'▷';$('#preview').setAttribute('aria-label',preview?'試聴を停止':'BGMを試聴');};$('#start').onclick=startGame;
}
async function initAudio(){try{await audio.init();}catch{notice('この環境では音楽を再生できません。音なしでもプレイできます。');}}
function wordRows(list){return list.map(w=>{const s=stats[w.id];return `<button class="word-row" data-word="${w.id}"><span><strong>${esc(w.word)}</strong><small>${esc(w.meaning)}</small></span><span><span class="pill">Lv.${w.level}</span><small>${s?.asked?pct(s.accuracy):'未学習'}</small></span></button>`;}).join('');}
function bindWords(root=main){root.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>showWord(b.dataset.word));}
function renderWords(){main.innerHTML=`<div class="eyebrow">YOUR VOCABULARY</div><h2>単語ライブラリ</h2><input id="wordSearch" type="search" placeholder="英単語・日本語で検索" aria-label="単語検索"><div class="row" style="margin-top:12px"><select id="wordLevel" aria-label="単語のレベル"><option value="0">すべてのレベル</option>${[1,2,3,4,5].map(n=>`<option value="${n}">Level ${n}</option>`).join('')}</select></div><p class="muted" id="wordCount"></p><div class="word-list" id="wordList"></div><button class="wide secondary" id="moreWords">さらに表示</button>`;let shown=50;const draw=()=>{const q=$('#wordSearch').value.trim().toLowerCase(),level=Number($('#wordLevel').value);const list=words.filter(w=>(!level||w.level===level)&&`${w.word} ${w.meaning} ${w.category}`.toLowerCase().includes(q));$('#wordCount').textContent=`${list.length}語 / ${words.length}語`;$('#wordList').innerHTML=wordRows(list.slice(0,shown))||'<p class="empty">一致する単語はありません。</p>';$('#moreWords').hidden=shown>=list.length;bindWords();};$('#wordSearch').oninput=()=>{shown=50;draw();};$('#wordLevel').onchange=()=>{shown=50;draw();};$('#moreWords').onclick=()=>{shown+=50;draw();};draw();}
function showWord(id){const w=words.find(w=>w.id===id);if(!w)return;const s=stats[id];$('#detailContent').innerHTML=`<div class="row between"><span class="eyebrow">LEVEL ${w.level} · ${esc(w.category)}</span><button class="icon-button" id="speakWord" aria-label="${esc(w.word)}を発音">♫</button></div><h2>${esc(w.word)}</h2><p class="detail-meta">/${esc(w.ipa)}/ · ${pos[w.partOfSpeech]}</p><h3>${esc(w.meaning)}</h3>${[1,2].map(n=>`<div class="example"><div class="example-head"><p>${esc(w['example'+n])}</p><button class="icon-button example-speak" data-example="${n}" aria-label="例文${n}を読み上げ">🔊</button></div><small>${esc(w['example'+n+'Ja'])}</small></div>`).join('')}<span class="label">COLLOCATIONS</span><p style="font-size:14px">${w.collocations.map(esc).join(' / ')}</p><p class="muted">${esc(w.note)}</p><div class="stats"><div><small>正答率</small><strong>${s?.asked?pct(s.accuracy):'—'}</strong></div><div><small>出題回数</small><strong>${s?.asked||0}</strong></div><div><small>習熟度</small><strong>${s?.mastery||0}</strong></div></div>${s?.asked?`<p class="muted">平均 ${sec(s.averageTime)} · 連続正解 ${s.streak}回<br>最終回答 ${new Date(s.lastAnswered).toLocaleString('ja-JP')}</p>`:''}`;$('#speakWord').onclick=async()=>{await initAudio();if(!audio.speak(w.word))notice('発音がOFF、またはこの環境では音声合成を利用できません。');};$('#detailContent').querySelectorAll('[data-example]').forEach(b=>b.onclick=async()=>{await initAudio();const n=b.dataset.example;if(!audio.speak(w['example'+n]))notice('発音がOFF、またはこの環境では音声合成を利用できません。');});$('#detail').showModal();}
function renderHistory(){main.innerHTML=`<div class="eyebrow">KEEP YOUR MOMENTUM</div><h2>学習のあしあと</h2><p class="muted">${sessions.length}プレイ · ${Object.keys(stats).length}語を学習</p>${sessions.length?[...sessions].sort((a,b)=>b.started.localeCompare(a.started)).map(s=>{const r=summarize(s.answers);return `<button class="history-item wide" style="text-align:left" data-session="${s.id}"><div class="row between"><span class="muted">${new Date(s.started).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span><span class="pill">${s.difficulty} · ${s.answers.length}問${s.completed?'':' / 中断'}</span></div><strong>${fmt(r.score)}</strong><p>正答率 ${pct(r.accuracy)} · 最大 ${r.bestCombo} COMBO · ${sec(r.averageTime)}</p></button>`;}).join(''):'<p class="empty">最初のビートを刻もう。<br>プレイすると、ここに記録が残ります。</p>'}`;main.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>renderResult(sessions.find(s=>s.id===b.dataset.session)));}
async function renderSettings(){main.innerHTML=`<div class="eyebrow">MAKE IT YOURS</div><h2>設定</h2><section class="card"><h3>サウンド</h3><label class="toggle">英単語・例文の発音<input type="checkbox" id="voiceOn" ${settings.voiceOn?'checked':''}></label>${[['bgm','BGM'],['voice','発音'],['se','効果音']].map(([k,l])=>`<label class="range-label" for="${k}">${l}<output id="${k}Value">${Math.round(settings[k]*100)}%</output></label><input id="${k}" type="range" min="0" max="100" value="${settings[k]*100}">`).join('')}<button id="testVoice" class="secondary wide">発音を試す · allocate</button><p class="muted">発音中はBGMを60%に下げます。オフラインの発音は、端末の英語音声に依存します。選択された音声によっては、単語の文字列が音声サービスへ送られます。</p></section><section class="card"><h3>端末内の保存</h3><div id="storageInfo" class="storage">確認中…</div><button class="secondary wide" id="persist">永続保存を申請</button><button class="secondary wide" id="retrySave">保存を再試行</button><p class="muted">履歴と設定はこのブラウザ内に保存されます。ブラウザのデータ削除や端末変更では引き継がれません。学習履歴を外部へ送信する機能はありません。</p></section><section class="card"><h3>ホーム画面・オフライン</h3><p class="muted">Chromeのメニューから「ホーム画面に追加」または「アプリをインストール」を選んでください。初回の読み込み後、ゲーム・単語・音楽はオフラインでも利用できます。</p><p class="muted" id="offlineInfo">キャッシュ状態を確認中…</p></section><p class="muted" style="font-size:11px">TOEIC BEAT v1.2.0<br>本アプリはTOEICの公式教材ではありません。レベル・重要度は本アプリ独自の分類で、出題頻度やスコアを保証するものではありません。例文とBGMはオリジナルです。</p>`;
 $('#voiceOn').onchange=e=>{settings.voiceOn=e.target.checked;persistSettings();};for(const k of ['bgm','voice','se'])$('#'+k).oninput=e=>{settings[k]=Number(e.target.value)/100;$('#'+k+'Value').textContent=e.target.value+'%';persistSettings();};$('#testVoice').onclick=async()=>{await initAudio();if(!audio.speak('allocate'))notice('発音をONにし、音量をご確認ください。');};$('#persist').onclick=async()=>{try{const granted=await navigator.storage?.persist?.();notice(granted?'永続保存が許可されています。':'永続保存は許可されませんでした。通常の端末保存は利用できます。');await storageInfo();}catch{notice('この環境では永続保存を申請できません。');}};$('#retrySave').onclick=async()=>{try{if(!db)db=await openDB();await saveSettings(db,settings);for(const s of sessions)await saveSession(db,s);for(const stat of Object.values(stats)){const last=sessions.at(-1);if(last)await saveProgress(db,stat,last);}notice('保存しました。');await storageInfo();}catch{notice('まだ保存できません。端末の空き容量やブラウザ設定をご確認ください。');}};await storageInfo();try{const keys=await caches.keys();if($('#offlineInfo'))$('#offlineInfo').textContent=keys.some(k=>k.startsWith('toeic-beat-'))?'オフライン用データの準備済み':'初回キャッシュを準備中です。オンラインで一度再読み込みしてください。';}catch{if($('#offlineInfo'))$('#offlineInfo').textContent='この環境ではオフライン保存を利用できません。';}}
async function storageInfo(){const size=new Blob([JSON.stringify({settings,stats,sessions})]).size;let persisted=false;try{persisted=await navigator.storage?.persisted?.();}catch{}if($('#storageInfo'))$('#storageInfo').textContent=`学習済み ${Object.keys(stats).length}語 / ${sessions.length}プレイ\n履歴・設定の概算 ${(size/1024).toFixed(1)} KB\n永続保存：${persisted?'許可済み':'通常保存'}${db?'':' / 現在保存できません'}`;}
function go(next){if(game)return;audio.stop();preview=false;page=['play','words','history','settings'].includes(next)?next:'play';document.body.classList.remove('game-mode');$('#nav').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({play:renderHome,words:renderWords,history:renderHistory,settings:renderSettings})[page]();window.scrollTo(0,0);}
async function startGame(){if(game)return;$('#start').disabled=true;const selected=selectWords(words,stats,settings.target,settings.count);if(!selected.length){notice('まだ苦手単語がありません。まずは全単語またはレベルを選んでプレイしてね。');$('#start').disabled=false;return;}await initAudio();if(!settings.persistenceRequested&&navigator.storage?.persist){settings.persistenceRequested=true;void navigator.storage.persist().catch(()=>{});persistSettings();}preview=false;audio.stop();const session={id:crypto.randomUUID(),started:new Date().toISOString(),difficulty:settings.difficulty,track:settings.track,target:settings.target,planned:selected.length,completed:false,answers:[]};sessions.push(session);game={session,selected,index:0,phase:'intro',paused:false,left:900,phaseStart:performance.now(),combo:0,score:0};document.body.classList.add('game-mode');main.innerHTML=`<section class="game"><div class="game-top"><div><small>SCORE</small><strong id="score">0</strong></div><div><small>COMBO</small><strong id="combo" class="combo">0</strong></div><span id="remaining" class="remaining">1 / ${selected.length}</span><button class="icon-button" id="pause" aria-label="一時停止">Ⅱ</button></div><div class="track-label">♫ ${esc(TRACKS.find(t=>t.id===settings.track).name)} · ${settings.difficulty}</div><div class="arena"><div class="lane"></div><div class="feedback" id="feedback" aria-live="polite"></div><div class="falling countdown" id="falling">READY</div><div class="combo-toast" id="comboToast"></div><div class="judgment-line"></div></div><div class="choices" id="choices"></div><div class="time-bar"><i id="timeFill"></i></div></section>`;$('#pause').onclick=pauseGame;audio.start();raf=requestAnimationFrame(frame);if(document.hidden)pauseGame();}
function nextQuestion(){if(!game)return;if(game.index>=game.selected.length){finishGame(true);return;}const w=game.selected[game.index];game.phase='question';game.left=LIMITS[game.session.difficulty];game.phaseStart=performance.now();game.elapsedBefore=0;$('#falling').classList.remove('countdown');$('#falling').innerHTML=`${esc(w.word)}<small>♪</small>`;$('#feedback').textContent='';$('#comboToast').textContent='';$('#remaining').textContent=`${game.index+1} / ${game.selected.length}`;$('#choices').innerHTML=choicesFor(w,words).map((c,i)=>`<button class="choice" data-answer="${c.id}"><small>${i+1}</small>${esc(c.meaning)}</button>`).join('');$('#choices').querySelectorAll('button').forEach(b=>b.onclick=()=>answer(b.dataset.answer));audio.speak(w.word);}
function rewardEffect(grade,target){
 if(grade==='MISS'||!target)return;
 target.classList.add('reward-'+grade.toLowerCase());
 setTimeout(()=>target.classList.remove('reward-'+grade.toLowerCase()),480);
 if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||grade==='GOOD')return;
 const rect=target.getBoundingClientRect(),burst=document.createElement('div');
 burst.className='reward-burst '+grade.toLowerCase();
 burst.style.left=(rect.left+rect.width/2)+'px';
 burst.style.top=(rect.top+rect.height/2)+'px';
 const count=grade==='PERFECT'?14:8,dist=grade==='PERFECT'?76:54;
 for(let i=0;i<count;i++){
  const p=document.createElement('i'),angle=(Math.PI*2*i/count)+(i%2?.12:-.08),r=dist*(.72+(i%3)*.12);
  p.style.setProperty('--dx',(Math.cos(angle)*r).toFixed(1)+'px');
  p.style.setProperty('--dy',(Math.sin(angle)*r).toFixed(1)+'px');
  p.style.setProperty('--delay',(i%4*12)+'ms');
  p.style.setProperty('--size',(i%3===0?7:i%3===1?5:3)+'px');
  burst.appendChild(p);
 }
 document.body.appendChild(burst);
 if(grade==='PERFECT'){
  const flash=document.createElement('div');
  flash.className='reward-flash';
  document.body.appendChild(flash);
  setTimeout(()=>flash.remove(),430);
 }
 setTimeout(()=>burst.remove(),520);
}
function frame(now){if(!game||game.paused)return;const elapsed=now-game.phaseStart;if(game.phase==='intro'){if(elapsed>=game.left)nextQuestion();}else if(game.phase==='question'){const limit=LIMITS[game.session.difficulty],spent=game.elapsedBefore+elapsed,f=Math.min(1,spent/limit);const travel=Math.max(0,$('.arena').clientHeight-40-$('#falling').offsetHeight);$('#falling').style.transform=`translateY(${f*travel}px)`;$('#timeFill').style.transform=`scaleX(${1-f})`;if(spent>=limit)answer(null);}else if(game.phase==='feedback'&&elapsed>=game.left){game.index++;nextQuestion();}if(game&&!game.paused)raf=requestAnimationFrame(frame);}
function answer(id){if(!game||game.paused||game.phase!=='question')return;const w=game.selected[game.index],limit=LIMITS[game.session.difficulty],elapsed=Math.min(limit,game.elapsedBefore+performance.now()-game.phaseStart),grade=judge(id===w.id,elapsed,limit);game.phase='feedback';game.left=audio.beatDelay(grade==='MISS'?600:300);game.phaseStart=performance.now();const a={wordId:w.id,chosen:id,grade,elapsed,limit,at:new Date().toISOString()};game.session.answers.push(a);stats[w.id]={id:w.id,...updateStat(stats[w.id],a)};const snapshot=structuredClone(game.session),stat={...stats[w.id]};if(db)queueSave(()=>saveProgress(db,stat,snapshot));game.score+=POINTS[grade];game.combo=grade==='MISS'?0:game.combo+1;$('#score').textContent=fmt(game.score);$('#combo').textContent=game.combo;$('#feedback').textContent=grade==='MISS'?`MISS · ${w.meaning}`:`${grade} +${POINTS[grade]}`;$('#feedback').classList.toggle('miss',grade==='MISS');let rewardTarget=null;$('#choices').querySelectorAll('button').forEach(b=>{b.disabled=true;if(b.dataset.answer===w.id){b.classList.add('correct');if(grade!=='MISS')rewardTarget=b;}else if(b.dataset.answer===id)b.classList.add('wrong');});rewardEffect(grade,rewardTarget);if(game.combo&&game.combo%10===0)$('#comboToast').textContent=`${game.combo} COMBO ✦`;audio.effect(grade);}
function pauseGame(){if(!game||game.paused)return;cancelAnimationFrame(raf);const elapsed=performance.now()-game.phaseStart;if(game.phase==='question')game.elapsedBefore+=elapsed;else game.left=Math.max(0,game.left-elapsed);game.paused=true;audio.stop();$('#pauseDialog').showModal();}
async function resumeGame(){if(!game)return;await initAudio();$('#pauseDialog').close();game.paused=false;game.phaseStart=performance.now();audio.start();if(game.phase==='question')audio.speak(game.selected[game.index].word);raf=requestAnimationFrame(frame);}
function finishGame(completed=false){if(!game)return;cancelAnimationFrame(raf);audio.stop();const s=game.session;s.completed=completed;s.finished=new Date().toISOString();game=null;$('#pauseDialog').close();if(db)queueSave(()=>saveSession(db,structuredClone(s)));document.body.classList.remove('game-mode');renderResult(s);}
function renderResult(s){const r=summarize(s.answers);main.innerHTML=`<div class="eyebrow">${s.completed?'SESSION COMPLETE':'SESSION RECORD'}</div><h2>${s.completed?'いいリズムだったね。':'ここまでの学習記録。'}</h2><div class="result-score"><div class="eyebrow">TOTAL SCORE</div><strong>${fmt(r.score)}</strong><span class="muted">${s.difficulty} · ${s.answers.length}問</span></div><section class="card"><div class="result-grade">${['PERFECT','GREAT','GOOD','MISS'].map(k=>`<div><small>${k}</small><strong>${r[k]}</strong></div>`).join('')}</div><div class="stats"><div><small>ACCURACY</small><strong>${pct(r.accuracy)}</strong></div><div><small>BEST COMBO</small><strong>${r.bestCombo}</strong></div><div><small>AVG. TIME</small><strong style="font-size:18px">${sec(r.averageTime)}</strong></div></div><p class="muted" style="font-size:10px;text-align:center;margin:0">平均回答時間には時間切れを含みます。</p></section><div class="row"><button id="again" class="primary" style="flex:1">もう一度プレイ →</button><button id="home" class="secondary">ホーム</button></div><div class="result-tabs"><button data-review="miss" class="selected">間違えた単語</button><button data-review="slow">時間がかかった</button><button data-review="weak">過去の苦手</button></div><div class="word-list" id="reviewList"></div>`;const draw=kind=>{let ids=kind==='miss'?s.answers.filter(a=>a.grade==='MISS').map(a=>a.wordId):kind==='slow'?s.answers.filter(a=>a.grade!=='MISS'&&a.elapsed>LIMITS[s.difficulty]*.7).sort((a,b)=>b.elapsed-a.elapsed).map(a=>a.wordId):Object.keys(stats).filter(id=>weak(stats[id])).sort((a,b)=>stats[a].accuracy-stats[b].accuracy);$('#reviewList').innerHTML=wordRows([...new Set(ids)].map(id=>words.find(w=>w.id===id)).filter(Boolean))||'<p class="empty">該当する単語はありません ✦</p>';bindWords();};main.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{main.querySelectorAll('[data-review]').forEach(x=>x.classList.toggle('selected',x===b));draw(b.dataset.review);});$('#home').onclick=()=>go('play');$('#again').onclick=()=>{go('play');startGame();};draw('miss');window.scrollTo(0,0);}
$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('.brand a').onclick=e=>{e.preventDefault();go('play');};$('#closeDetail').onclick=()=>{$('#detail').close();audio.cancelVoice();};$('#detail').addEventListener('close',()=>audio.cancelVoice());$('#resume').onclick=resumeGame;$('#quit').onclick=()=>finishGame(false);$('#pauseDialog').addEventListener('cancel',e=>e.preventDefault());document.addEventListener('visibilitychange',()=>{if(document.hidden){if(game)pauseGame();else{audio.stop();preview=false;if($('#preview')){$('#preview').textContent='▷';$('#preview').setAttribute('aria-label','BGMを試聴');}}}});window.addEventListener('keydown',e=>{if(game&&!e.repeat){if(e.key==='Escape'){pauseGame();return;}if(/^[1-4]$/.test(e.key)){const b=$('#choices')?.children[Number(e.key)-1];if(b&&!b.disabled)b.click();}}});
try{const res=await fetch('./words.json');if(!res.ok)throw Error('単語データを読み込めません');words=await res.json();try{db=await openDB();const [st,ss,se]=await Promise.all([all(db,'stats'),all(db,'settings'),all(db,'sessions')]);stats=Object.fromEntries(st.map(s=>[s.id,s]));settings={...defaults,...ss.find(s=>s.id==='main')};if(!LIMITS[settings.difficulty])settings.difficulty='NORMAL';if(!TRACKS.some(t=>t.id===settings.track))settings.track='focus';sessions=se;audio.update(settings);}catch{notice('端末保存を利用できません。プレイできますが、閉じると記録が失われます。');}go('play');if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>notice('オフライン準備に失敗しました。オンラインで再読み込みしてください。'));}catch(e){main.innerHTML='<p class="empty">読み込みに失敗しました。オンラインで再読み込みしてください。</p>';console.error(e);}
