import {TRACKS} from './tracks.js';
export class BeatAudio {
 constructor(){this.settings={bgm:.38,voice:.85,se:.55,voiceOn:true,track:'focus'};this.timer=null;this.ducked=false;this.voiceToken=0;this.active=new Set();this.voices=[];if('speechSynthesis' in window){this.refreshVoices();speechSynthesis.addEventListener('voiceschanged',()=>this.refreshVoices());}}
 refreshVoices(){this.voices=speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang));}
 async init(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.bgm=this.ctx.createGain();this.se=this.ctx.createGain();this.bgm.connect(this.ctx.destination);this.se.connect(this.ctx.destination);const n=this.ctx.sampleRate;this.noise=this.ctx.createBuffer(1,n,this.ctx.sampleRate);const a=this.noise.getChannelData(0);for(let i=0;i<n;i++)a[i]=Math.random()*2-1;}if(this.ctx.state==='suspended')await this.ctx.resume();this.update(this.settings);}
 update(s){this.settings={...this.settings,...s};if(this.ctx){this.bgm.gain.setTargetAtTime(this.settings.bgm*(this.ducked?.6:1),this.ctx.currentTime,.06);this.se.gain.setTargetAtTime(this.settings.se,this.ctx.currentTime,.03);}}
 tone(freq,t,dur,vol=.1,wave='sine',out=this.bgm){const c=this.ctx;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=wave;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(out);o.start(t);o.stop(t+dur+.02);this.active.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.active.delete(o);};}
 percussion(kind,t){const c=this.ctx;if(kind==='kick'){const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(42,t+.14);g.gain.setValueAtTime(.25,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g);g.connect(this.bgm);o.start(t);o.stop(t+.2);this.active.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.active.delete(o);};return;}const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noise;f.type='highpass';f.frequency.value=kind==='hat'?6500:1600;const dur=kind==='hat'?.035:.1;g.gain.setValueAtTime(kind==='hat'?.045:.09,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);n.connect(f);f.connect(g);g.connect(this.bgm);n.start(t);n.stop(t+dur);this.active.add(n);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();this.active.delete(n);};}
 start(id=this.settings.track){this.stopMusic();if(!this.ctx)return;this.track=TRACKS.find(x=>x.id===id)||TRACKS[0];this.step=0;this.next=this.ctx.currentTime+.07;this.origin=this.next;const tick=()=>{while(this.next<this.ctx.currentTime+.12){this.schedule(this.step,this.next);this.step++;this.next=this.origin+this.step*60/this.track.bpm/4;}};tick();this.timer=setInterval(tick,25);}
 schedule(step,t){const tr=this.track,s=step%16,bar=Math.floor(step/16)%4;const when=t+(s%2?tr.swing*60/tr.bpm/4:0);for(const kind of ['kick','snare','hat'])if(tr[kind].includes(s))this.percussion(kind,when);const root=tr.roots[bar],hz=n=>440*2**((n-69)/12);if(tr.bass.includes(s))this.tone(hz(root-12+(s===14?7:0)),when,.25,.16,'sine');if(s===0 || (tr.id==='city' && [6,10,14].includes(s))){for(const note of tr.chord)this.tone(hz(root+note),when,tr.id==='night'?1.7:.65,.022,tr.wave);}if(tr.melody[s]!=null)this.tone(hz(root+12+tr.melody[s]),when,.17,.023,tr.wave);}
 beatDelay(minMs){if(!this.ctx||!this.timer)return minMs;const beat=60/this.track.bpm;const earliest=this.ctx.currentTime+minMs/1000;const snap=this.origin+Math.ceil((earliest-this.origin)/(beat/2))*(beat/2);return minMs+Math.min(180,Math.max(0,(snap-earliest)*1000));}
 stopMusic(){clearInterval(this.timer);this.timer=null;for(const n of this.active){try{n.stop();}catch{}}this.active.clear();}
 duck(on){this.ducked=on;this.update({});}
 speak(word){this.cancelVoice();if(!this.settings.voiceOn||!this.settings.voice||!('speechSynthesis' in window))return false;const token=++this.voiceToken,u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.volume=this.settings.voice;u.rate=1;u.voice=this.voices.find(v=>v.localService&&/^en-US/i.test(v.lang))||this.voices.find(v=>/^en-US/i.test(v.lang))||this.voices[0]||null;const end=()=>{if(token===this.voiceToken){clearTimeout(this.duckTimeout);this.duck(false);}};u.onstart=()=>{if(token===this.voiceToken)this.duck(true);};u.onend=end;u.onerror=end;this.duckTimeout=setTimeout(end,4500);speechSynthesis.speak(u);return true;}
 cancelVoice(){this.voiceToken++;clearTimeout(this.duckTimeout);if('speechSynthesis' in window)speechSynthesis.cancel();this.duck(false);}
 spark(t,vol=.08){const c=this.ctx;if(!c||!this.noise)return;const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noise;f.type='highpass';f.frequency.setValueAtTime(5200,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+.08);n.connect(f);f.connect(g);g.connect(this.se);n.start(t);n.stop(t+.085);this.active.add(n);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();this.active.delete(n);};}
 effect(grade){if(!this.ctx)return;const t=this.ctx.currentTime;if(grade==='MISS'){this.tone(170,t,.11,.12,'triangle',this.se);this.tone(120,t+.045,.09,.07,'sine',this.se);return;}const p=grade==='PERFECT'?{base:880,gain:.24}:grade==='GREAT'?{base:760,gain:.20}:{base:660,gain:.17};this.spark(t,.075);this.tone(p.base,t,.11,p.gain,'triangle',this.se);this.tone(p.base*1.5,t+.035,.13,p.gain*.68,'sine',this.se);if(grade!=='GOOD')this.tone(p.base*2,t+.075,.16,p.gain*.55,'sine',this.se);if(grade==='PERFECT'){this.tone(p.base*2.5,t+.12,.18,p.gain*.42,'sine',this.se);this.spark(t+.09,.05);}}
 stop(){this.stopMusic();this.cancelVoice();}
}
