import {TRACKS} from './tracks.js';
export class BeatAudio {
 constructor(){this.settings={bgm:.38,voice:.85,se:.55,voiceOn:true,track:'focus'};this.timer=null;this.ducked=false;this.voiceToken=0;this.voiceFinish=null;this.musicToken=0;this.fileSource=null;this.customBlobs=new Map();this.customBuffers=new Map();this.fileBuffers=new Map();this.active=new Set();this.voices=[];if('speechSynthesis' in window){this.refreshVoices();speechSynthesis.addEventListener('voiceschanged',()=>this.refreshVoices());}}
 refreshVoices(){this.voices=speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang));}
 async init(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.bgm=this.ctx.createGain();this.se=this.ctx.createGain();this.bgm.connect(this.ctx.destination);this.se.connect(this.ctx.destination);const n=this.ctx.sampleRate;this.noise=this.ctx.createBuffer(1,n,this.ctx.sampleRate);const a=this.noise.getChannelData(0);for(let i=0;i<n;i++)a[i]=Math.random()*2-1;}if(this.ctx.state==='suspended')await this.ctx.resume();this.update(this.settings);}
 update(s){this.settings={...this.settings,...s};if(this.ctx){this.bgm.gain.setTargetAtTime(this.settings.bgm*(this.ducked?.6:1),this.ctx.currentTime,.06);this.se.gain.setTargetAtTime(this.settings.se,this.ctx.currentTime,.03);}}
 setCustomTrackBlob(blob,id='sunlight'){if(blob)this.customBlobs.set(id,blob);else this.customBlobs.delete(id);this.customBuffers.delete(id);}
 hasCustomTrack(id='sunlight'){return this.customBlobs.has(id);}
 tone(freq,t,dur,vol=.1,wave='sine',out=this.bgm){const c=this.ctx;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=wave;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(out);o.start(t);o.stop(t+dur+.02);this.active.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.active.delete(o);};}
 percussion(kind,t){const c=this.ctx;if(kind==='kick'){const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(42,t+.14);g.gain.setValueAtTime(.25,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g);g.connect(this.bgm);o.start(t);o.stop(t+.2);this.active.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.active.delete(o);};return;}const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noise;f.type='highpass';f.frequency.value=kind==='hat'?6500:1600;const dur=kind==='hat'?.035:.1;g.gain.setValueAtTime(kind==='hat'?.045:.09,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);n.connect(f);f.connect(g);g.connect(this.bgm);n.start(t);n.stop(t+dur);this.active.add(n);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();this.active.delete(n);};}
 async start(id=this.settings.track){this.stopMusic();if(!this.ctx)return false;this.track=TRACKS.find(x=>x.id===id)||TRACKS[0];const token=this.musicToken;if(this.track.embeddedParts)return this.startEmbedded(this.track,token);if(this.track.custom)return this.startCustom(this.track,token);this.step=0;this.next=this.ctx.currentTime+.07;this.origin=this.next;const tick=()=>{while(this.next<this.ctx.currentTime+.12){this.schedule(this.step,this.next);this.step++;this.next=this.origin+this.step*60/this.track.bpm/4;}};tick();this.timer=setInterval(tick,25);return true;}
 async decodeEmbedded(track){if(this.fileBuffers.has(track.id))return this.fileBuffers.get(track.id);const jobs=[];for(let i=0;i<track.embeddedParts;i++){const part=String(i).padStart(2,'0');jobs.push(fetch(new URL(`${track.partPrefix}${part}.txt`,document.baseURI)).then(r=>{if(!r.ok)throw Error(`Audio part ${part}: ${r.status}`);return r.text();}));}const encoded=(await Promise.all(jobs)).join('').replace(/\s+/g,'');const raw=atob(encoded),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const buffer=await this.ctx.decodeAudioData(bytes.buffer);this.fileBuffers.set(track.id,buffer);return buffer;}
 async startEmbedded(track,token){try{const buffer=await this.decodeEmbedded(track);if(token!==this.musicToken)return false;return this.playBuffer(track,buffer);}catch(e){console.error('Embedded track could not be decoded',e);return false;}}
 async startCustom(track,token){const id=track.storageId||track.id,blob=this.customBlobs.get(id);if(!blob)return false;try{let buffer=this.customBuffers.get(id);if(!buffer){const bytes=await blob.arrayBuffer();buffer=await this.ctx.decodeAudioData(bytes.slice(0));this.customBuffers.set(id,buffer);}if(token!==this.musicToken)return false;return this.playBuffer(track,buffer);}catch(e){console.error('Custom track could not be decoded',e);return false;}}
 playBuffer(track,buffer){const source=this.ctx.createBufferSource(),duration=buffer.duration;source.buffer=buffer;source.loop=true;source.loopStart=Math.min(track.loopStart||0,Math.max(0,duration-.1));source.loopEnd=Math.max(source.loopStart+.1,Math.min(track.loopEnd||duration,duration));source.connect(this.bgm);this.fileSource=source;this.origin=this.ctx.currentTime;this.active.add(source);source.onended=()=>{source.disconnect();this.active.delete(source);if(this.fileSource===source)this.fileSource=null;};source.start(0,source.loopStart);return true;}
 schedule(step,t){const tr=this.track,s=step%16,bar=Math.floor(step/16)%4;const when=t+(s%2?tr.swing*60/tr.bpm/4:0);for(const kind of ['kick','snare','hat'])if(tr[kind].includes(s))this.percussion(kind,when);const root=tr.roots[bar],hz=n=>440*2**((n-69)/12);if(tr.bass.includes(s))this.tone(hz(root-12+(s===14?7:0)),when,.25,.16,'sine');if(s===0||(tr.id==='city'&&[6,10,14].includes(s))){for(const note of tr.chord)this.tone(hz(root+note),when,tr.id==='night'?1.7:.65,.022,tr.wave);}if(tr.melody[s]!=null)this.tone(hz(root+12+tr.melody[s]),when,.17,.023,tr.wave);}
 beatDelay(minMs){if(!this.ctx||(!this.timer&&!this.fileSource))return minMs;const beat=60/this.track.bpm;const earliest=this.ctx.currentTime+minMs/1000;const snap=this.origin+Math.ceil((earliest-this.origin)/(beat/2))*(beat/2);return minMs+Math.min(180,Math.max(0,(snap-earliest)*1000));}
 stopMusic(){this.musicToken++;clearInterval(this.timer);this.timer=null;this.fileSource=null;for(const n of this.active){try{n.stop();}catch{}}this.active.clear();}
 duck(on){this.ducked=on;this.update({});}
 speak(text,onDone){this.cancelVoice();if(!this.settings.voiceOn||!this.settings.voice||!('speechSynthesis' in window)){onDone?.();return false;}const token=++this.voiceToken,u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.volume=this.settings.voice;u.rate=1;u.voice=this.voices.find(v=>v.localService&&/^en-US/i.test(v.lang))||this.voices.find(v=>/^en-US/i.test(v.lang))||this.voices[0]||null;let settled=false;const complete=()=>{if(settled)return;settled=true;clearTimeout(this.duckTimeout);if(token===this.voiceToken){this.voiceFinish=null;this.duck(false);}onDone?.();};this.voiceFinish=complete;u.onstart=()=>{if(token===this.voiceToken)this.duck(true);};u.onend=complete;u.onerror=complete;const fallback=Math.max(6000,Math.min(15000,String(text).length*130));this.duckTimeout=setTimeout(complete,fallback);speechSynthesis.speak(u);return true;}
 cancelVoice(){const finish=this.voiceFinish;this.voiceFinish=null;this.voiceToken++;clearTimeout(this.duckTimeout);if('speechSynthesis' in window)speechSynthesis.cancel();this.duck(false);finish?.();}
 spark(t,vol=.08){const c=this.ctx;if(!c||!this.noise)return;const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noise;f.type='highpass';f.frequency.setValueAtTime(5200,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+.08);n.connect(f);f.connect(g);g.connect(this.se);n.start(t);n.stop(t+.085);this.active.add(n);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();this.active.delete(n);};}
 effect(grade){if(!this.ctx)return;const t=this.ctx.currentTime;if(grade==='MISS'){this.tone(165,t,.12,.14,'triangle',this.se);this.tone(112,t+.045,.11,.09,'sine',this.se);return;}const good=grade==='GOOD',great=grade==='GREAT',perfect=grade==='PERFECT';const base=good?760:great?900:1040,gain=good?.28:great?.36:.44;this.spark(t,good?.11:great?.15:.20);this.tone(base/2,t,.12,gain*.38,'sine',this.se);this.tone(base,t,.12,gain,'triangle',this.se);this.tone(base*1.5,t+.032,.15,gain*.78,'sine',this.se);this.tone(base*2,t+.072,.18,gain*.62,'sine',this.se);if(great||perfect){this.tone(base*2.5,t+.115,.20,gain*.50,'triangle',this.se);this.spark(t+.085,great?.10:.14);}if(perfect){this.tone(base*3,t+.16,.24,gain*.44,'sine',this.se);this.tone(base*4,t+.205,.22,gain*.30,'sine',this.se);this.spark(t+.15,.12);}}
 stop(){this.stopMusic();this.cancelVoice();}
}
