export const LIMITS={EASY:4000,NORMAL:3000,HARD:2000,EXPERT:1500};
export const POINTS={PERFECT:100,GREAT:80,GOOD:50,MISS:0};
export const blankStat=()=>({asked:0,correct:0,incorrect:0,perfect:0,great:0,good:0,totalTime:0,totalRatio:0,averageRatio:0,averageTime:0,lastAnswered:null,streak:0,mastery:0,accuracy:0});
export function judge(correct,elapsed,limit){return !correct||elapsed>=limit?'MISS':elapsed<=limit*.35?'PERFECT':elapsed<=limit*.7?'GREAT':'GOOD';}
export function updateStat(old,answer){const s={...blankStat(),...old};s.asked++;s.totalTime+=answer.elapsed;s.totalRatio+=(answer.elapsed/(answer.limit||3000));s.averageRatio=s.totalRatio/s.asked;s.averageTime=s.totalTime/s.asked;s.lastAnswered=answer.at;if(answer.grade==='MISS'){s.incorrect++;s.streak=0;}else{s.correct++;s.streak++;s[answer.grade.toLowerCase()]++;}s.accuracy=s.correct/s.asked;s.mastery=Math.min(100,Math.round(s.accuracy*65+Math.min(s.streak,5)*5+Math.min(s.asked,10)));return s;}
export function weak(s){return !!s?.asked&&(s.accuracy<.8||s.mastery<65||s.averageRatio>.7);}
export function weight(s){if(!s?.asked)return 2.5;return Math.max(.3,1+(1-s.accuracy)*4+Math.min(2,s.averageTime/2000)-(s.mastery>90?1:0));}
export function selectWords(words,stats,target,count,rng=Math.random){let pool=words.filter(w=>target==='weak'?weak(stats[w.id]):/^level/.test(target)?w.level===Number(target.slice(5)):true);const selected=[];while(pool.length&&selected.length<count){const weights=pool.map(w=>weight(stats[w.id])*(target==='new'&&!stats[w.id]?.asked?20:1));let t=rng()*weights.reduce((a,b)=>a+b,0),i=0;while(i<pool.length-1&&(t-=weights[i])>0)i++;selected.push(pool.splice(i,1)[0]);}return selected;}
export function shuffle(a,rng=Math.random){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function choicesFor(word,words,rng=Math.random){const seen=new Set([word.meaning,...(word.excludeMeanings||[])]);const pool=shuffle(words.filter(w=>w.partOfSpeech===word.partOfSpeech&&w.id!==word.id),rng).sort((a,b)=>(b.category===word.category)-(a.category===word.category));const distractors=[];for(const w of pool){if(!seen.has(w.meaning)&&!word.synonyms?.includes(w.word)){seen.add(w.meaning);distractors.push({id:w.id,meaning:w.meaning});if(distractors.length===3)break;}}if(distractors.length!==3)throw Error('選択肢を作成できません');return shuffle([{id:word.id,meaning:word.meaning},...distractors],rng);}
export function summarize(answers){const result={score:0,accuracy:0,bestCombo:0,averageTime:0,PERFECT:0,GREAT:0,GOOD:0,MISS:0};let combo=0;for(const a of answers){result[a.grade]++;result.score+=POINTS[a.grade];combo=a.grade==='MISS'?0:combo+1;result.bestCombo=Math.max(result.bestCombo,combo);result.averageTime+=a.elapsed;}if(answers.length){result.accuracy=(answers.length-result.MISS)/answers.length;result.averageTime/=answers.length;}return result;}
