import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {LIMITS,judge,updateStat,selectWords,choicesFor,summarize,weak,weight} from '../core.js';
import {TRACKS} from '../tracks.js';
const words=JSON.parse(readFileSync(new URL('../words.json',import.meta.url)));
test('500 unique words, 100 per level and 1,000 complete distinct bilingual examples',()=>{
 assert.equal(words.length,500);assert.equal(new Set(words.map(w=>w.word)).size,500);
 for(const level of [1,2,3,4,5])assert.equal(words.filter(w=>w.level===level).length,100);
 for(const w of words){for(const k of ['id','word','meaning','ipa','partOfSpeech','category','example1','example1Ja','example2','example2Ja'])assert.ok(w[k],w.word+':'+k);assert.notEqual(w.example1,w.example2);assert.equal(w.collocations.length,2);for(const k of ['example1','example2'])assert.ok(w[k].split(/\s+/).length<=20);}
 assert.equal(new Set(words.flatMap(w=>[w.example1,w.example2])).size,1000);
});
test('judgement boundaries and late taps across every speed',()=>{for(const limit of Object.values(LIMITS)){assert.equal(judge(true,0,limit),'PERFECT');assert.equal(judge(true,limit*.35,limit),'PERFECT');assert.equal(judge(true,limit*.35+1,limit),'GREAT');assert.equal(judge(true,limit*.7+1,limit),'GOOD');assert.equal(judge(true,limit,limit),'MISS');assert.equal(judge(false,1,limit),'MISS');}});
test('4 distinct choices, exactly one correct, same POS and no excluded synonyms',()=>{for(const w of words)for(let r=0;r<10;r++){const cs=choicesFor(w,words);assert.equal(cs.length,4);assert.equal(cs.filter(c=>c.id===w.id).length,1);assert.equal(new Set(cs.map(c=>c.meaning)).size,4);for(const c of cs.filter(c=>c.id!==w.id)){assert.ok(!w.excludeMeanings.includes(c.meaning));assert.equal(words.find(x=>x.id===c.id).partOfSpeech,w.partOfSpeech);}}});
test('target filters, no repeats, empty weak list and short pool',()=>{assert.equal(selectWords(words,{},'weak',20).length,0);for(const target of ['all','new','level1','level2','level3','level4','level5']){const a=selectWords(words,{},target,50);assert.equal(a.length,50);assert.equal(new Set(a.map(w=>w.id)).size,50);if(target.startsWith('level'))assert.ok(a.every(w=>w.level===+target.at(-1)));}const w=words[0],s={[w.id]:{asked:1,accuracy:0,averageTime:3000,mastery:0}};assert.equal(selectWords(words,s,'weak',20).length,1);});
test('statistics keep all attempts, streak resets, slow correct words remain weak',()=>{let s=updateStat(null,{grade:'PERFECT',elapsed:300,limit:3000,at:'2026-09-11T00:00:00Z'});s=updateStat(s,{grade:'MISS',elapsed:3000,limit:3000,at:'2026-09-11T00:01:00Z'});assert.equal(s.asked,2);assert.equal(s.correct,1);assert.equal(s.incorrect,1);assert.equal(s.streak,0);assert.equal(s.accuracy,.5);assert.equal(s.averageTime,1650);assert.equal(s.perfect,1);assert.ok(weak(s));let slow=null;for(let i=0;i<10;i++)slow=updateStat(slow,{grade:'GOOD',elapsed:2900,limit:3000,at:'2026-09-11'});assert.ok(weak(slow));assert.ok(weight({...slow,accuracy:0})>weight({...slow,accuracy:1,mastery:100}));assert.ok(weight({...slow,accuracy:1,mastery:100})>0);});
test('score and best combo correctly reflect misses and incomplete sessions',()=>{const r=summarize(['PERFECT','GREAT','MISS','GOOD','PERFECT','GREAT'].map(grade=>({grade,elapsed:1000})));assert.equal(r.score,410);assert.equal(r.bestCombo,3);assert.equal(r.MISS,1);assert.equal(r.accuracy,5/6);assert.equal(r.averageTime,1000);assert.equal(summarize([]).accuracy,0);});
test('five distinct compositions, all notes and tempo data finite',()=>{assert.equal(TRACKS.length,5);assert.equal(new Set(TRACKS.map(t=>JSON.stringify([t.roots,t.melody,t.kick]))).size,5);for(const t of TRACKS){assert.ok(t.bpm>=105&&t.bpm<=140);assert.equal(t.melody.length,16);assert.equal(t.roots.length,4);}});
